/**
 * CopilotPanel — lazy-loaded wrapper around ChatKit StudioCopilot.
 *
 * Kept in its own file so React.lazy() can defer the import until the user
 * first opens the panel.
 */
import { useEffect, useRef } from 'react';
import type { ComponentType } from 'react';
import { StudioCopilot } from '@kweaver-ai/chatkit';
import { getAgentConfigForView, getContextForView } from '../../utils/copilotConfig';
import { dipEnvironmentService } from '../../services/dipEnvironmentService';
import { getAuthToken } from '../../config/apiConfig';

type ViewType = 'cockpit' | 'search' | 'planningV2' | 'procurementWorkbench' | 'inventory' | 'optimization' | 'delivery' | 'evaluation' | 'config';

interface CopilotPanelProps {
  currentView: ViewType;
  onClose: () => void;
}

// StudioCopilot is generated by the SDK mixin; its runtime component works, but
// the generated d.ts does not expose a JSX-compatible constructor type.
const StudioCopilotComponent = StudioCopilot as unknown as ComponentType<any>;

const CopilotPanel = ({ currentView, onClose }: CopilotPanelProps) => {
  const copilotRef = useRef<StudioCopilot>(null);
  const { agentId, title } = getAgentConfigForView(currentView);

  useEffect(() => {
    const ctx = getContextForView(currentView);
    if (ctx && copilotRef.current) {
      copilotRef.current.injectApplicationContext(ctx);
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <StudioCopilotComponent
      ref={copilotRef}
      title={title}
      visible={true}
      onClose={onClose}
      baseUrl="/api/dip-studio/v1"
      agentId={agentId}
      userId="studio-demo-user"
      token={getAuthToken()}
      refreshToken={async () => {
        const t = dipEnvironmentService.isDipMode()
          ? await dipEnvironmentService.refreshToken()
          : getAuthToken();
        if (!t) return '';
        // Strip accidental "Bearer " prefix; StudioCopilot adds it internally.
        return t.startsWith('Bearer ') ? t.slice(7) : t;
      }}
      assistantName={title}
    />
  );
};

export default CopilotPanel;
